In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [25]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [26]:
pd.set_option('display.max_columns',None)
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [27]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [28]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [29]:
movies=movies.merge(credits,on='title')

In [30]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [31]:
# genres,id,keywords,title,overview,cast,crew

In [32]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [33]:
movies=movies[['movie_id','title','genres','overview','keywords','cast','crew']]

In [34]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [35]:
movies.isnull().sum()

movie_id    0
title       0
genres      0
overview    3
keywords    0
cast        0
crew        0
dtype: int64

In [36]:
movies.dropna(inplace=True)

In [37]:
movies.isnull().sum()

movie_id    0
title       0
genres      0
overview    0
keywords    0
cast        0
crew        0
dtype: int64

In [38]:
movies.duplicated().sum()

0

In [46]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [49]:
def convert(x):
    l=[]
    for i in eval(x):
        l.append(i['name'])
    return l

In [51]:
movies['genres']=movies['genres'].apply(convert)

In [52]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [54]:
movies['keywords']=movies['keywords'].apply(convert)

In [55]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [59]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [96]:
def convert1(x):
    l=[]
    c=0
    for i in eval(x):
        if c<3:
            l.append(i['name'])
            c+=1
        else:
            break
    return l

In [100]:
movies['cast']=movies['cast'].apply(convert1)

In [101]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [120]:
for i in eval(movies['crew'][0]):
    if i['job'] == 'Director':
        print(i['name'])

James Cameron

In [125]:
def director_name(x):
    l=[]
    for i in eval(x):
        if i['job'] == 'Director':
            l.append(i['name'])
            break
    return l

In [127]:
movies['crew']=movies['crew'].apply(director_name)

In [128]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [129]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [131]:
movies['overview']=movies['overview'].apply(lambda x :x.split())

In [132]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send...","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[John, Carter, is, a, war-weary,, former, mili...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [135]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(' ','') for i in x])

In [136]:
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(' ','') for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(' ','') for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(' ','') for i in x])

In [137]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [138]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [139]:
movies.head(1)

,movie_id,title,genres,overview,keywords,cast,crew,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."

In [142]:
new_df = movies[['movie_id','title','tags']]

In [143]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [146]:
new_df['tags']=new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\User\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [147]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [151]:
new_df.iloc[0].tags

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [152]:
new_df['tags'] = new_df['tags'].apply(lambda x : x.lower())

C:\Users\User\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [153]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [154]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2000,stop_words='english')

In [157]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [164]:
cv.get_feature_names()

['000',
 '10',
 '11',
 '12',
 '14',
 '15',
 '17',
 '18',
 '1930s',
 '1950s',
 '1960s',
 '1970s',
 '1980s',
 '19th',
 '19thcentury',
 '20',
 '30',
 '3d',
 'aaroneckhart',
 'abandoned',
 'ability',
 'able',
 'abuse',
 'academy',
 'accident',
 'accidentally',
 'accused',
 'act',
 'action',
 'actions',
 'actor',
 'actress',
 'actually',
 'adam',
 'adamsandler',
 'adaptation',
 'addiction',
 'adoption',
 'adult',
 'adultery',
 'adventure',
 'adventures',
 'advice',
 'affair',
 'africa',
 'african',
 'aftercreditsstinger',
 'afterlife',
 'age',
 'agent',
 'agents',
 'aging',
 'ago',
 'agrees',
 'ahead',
 'aid',
 'air',
 'airplane',
 'airport',
 'alaska',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alice',
 'alien',
 'alieninvasion',
 'aliens',
 'alive',
 'allies',
 'alpacino',
 'alter',
 'amazing',
 'ambitious',
 'america',
 'american',
 'americanfootball',
 'americans',
 'amnesia',
 'amp',
 'ancient',
 'anderson',
 'android',
 'andy',
 'angel',
 'angeles',
 'angelinajolie',
 'animal',
 'animals',
 'animated',
 'animation',
 'anna',
 'anne',
 'annehathaway',
 'annie',
 'annual',
 'answers',
 'anthonyhopkins',
 'anti',
 'antihero',
 'antoniobanderas',
 'apart',
 'apartment',
 'apocalypse',
 'apocalyptic',
 'appears',
 'archaeologist',
 'area',
 'armed',
 'army',
 'arnoldschwarzenegger',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'art',
 'arthur',
 'artificialintelligence',
 'artist',
 'arts',
 'asks',
 'aspiring',
 'assassin',
 'assassination',
 'assigned',
 'assignment',
 'assistant',
 'astronaut',
 'asylum',
 'attack',
 'attempt',
 'attempts',
 'attorney',
 'aunt',
 'australia',
 'australian',
 'author',
 'authorities',
 'avoid',
 'award',
 'away',
 'awry',
 'baby',
 'bachelor',
 'bad',
 'balance',
 'ballet',
 'band',
 'bank',
 'bar',
 'barry',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedonnovel',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basketball',
 'batman',
 'battle',
 'beach',
 'bear',
 'beat',
 'beautiful',
 'beauty',
 'becominganadult',
 'bed',
 'befriends',
 'begin',
 'beginning',
 'begins',
 'believe',
 'believes',
 'beloved',
 'ben',
 'benaffleck',
 'benkingsley',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bet',
 'betrayal',
 'better',
 'bible',
 'big',
 'biggest',
 'billy',
 'biography',
 'birth',
 'birthday',
 'bizarre',
 'black',
 'blackmail',
 'blackpeople',
 'blind',
 'blood',
 'bloody',
 'blue',
 'board',
 'boat',
 'bob',
 'bobby',
 'body',
 'bodyguard',
 'bomb',
 'bond',
 'book',
 'border',
 'born',
 'boss',
 'boston',
 'bound',
 'bounty',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'bradpitt',
 'break',
 'breaks',
 'brian',
 'bride',
 'bridge',
 'brilliant',
 'bring',
 'brings',
 'britain',
 'british',
 'broadway',
 'broken',
 'brooklyn',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'brucewillis',
 'brutal',
 'buddy',
 'build',
 'building',
 'bully',
 'buried',
 'bus',
 'business',
 'businessman',
 'cabin',
 'california',
 'called',
 'calls',
 'calvin',
 'came',
 'camerondiaz',
 'camp',
 'campaign',
 'campus',
 'canada',
 'cancer',
 'captain',
 'capture',
 'captured',
 'car',
 'carchase',
 'carcrash',
 'care',
 'career',
 'carl',
 'carter',
 'case',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'catch',
 'cateblanchett',
 'catherinekeener',
 'catholic',
 'caught',
 'cause',
 'causing',
 'cave',
 'celebration',
 'celebrity',
 'center',
 'centered',
 'century',
 'certain',
 'chain',
 'challenge',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'chaos',
 'character',
 'characters',
 'charge',
 'charles',
 'charlie',
 'charlizetheron',
 'charming',
 'chase',
 'cheating',
 'chicago',
 'chief',
 'child',
 'childhood',
 'children',
 'china',
 'chinese',
 'choice',
 'choose',
 'chosen',
 'chris',
 'christian',
 'christianbale',
 'christmas',
 'christopherplummer',
 'church',
 'cia',
 'circus',
 'city',
 'civil',
 'claim',
 'claims',
 'class',
 'classic',
 'clean',
 'clear',
 'clerk',
 'clinteastwood',
 'clone',
 'close',
 'closer',
 'club',
 'clues',
 'coach',
 'cocaine',
 'code',
 'cold',
 'coldwar',
 'colinfarrell',
 'collection',
 'college',
 'collide',
 'coma',
 'combat',
 'come',
 'comedy',
 'comes',
 'comic',
 'coming',
 'comingofage',
 'common',
 'community',
 'company',
 'compete',
 'competition',
 'complete',
 'complicated',
 'computer',
 'concert',
 'conflict',
 'confront',
 'connection',
 'connor',
 'consequences',
 'conspiracy',
 'contact',
 'contest',
 'continue',
 'continues',
 'contract',
 'control',
 'controversial',
 'convict',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cop',
 'cops',
 'corporate',
 'corporation',
 'corpse',
 'corrupt',
 'corruption',
 'count',
 'country',
 'countryside',
 'couple',
 'couples',
 'courage',
 'course',
 'court',
 'cousin',
 'cover',
 'cowardliness',
 'crash',
 'crazy',
 'create',
 'created',
 'creates',
 'creature',
 'creatures',
 'crew',
 'crime',
 'crimes',
 'criminal',
 'criminals',
 'crisis',
 'cross',
 'crush',
 'cuba',
 'cult',
 'culture',
 'cure',
 'curse',
 'cut',
 'dad',
 'daily',
 'dan',
 'dance',
 'dancer',
 'dancing',
 'danger',
 'dangerous',
 'danny',
 'dannydevito',
 'dark',
 'darkcomedy',
 'darkness',
 'date',
 'dating',
 'daughter',
 'daughters',
 'david',
 'day',
 'days',
 'dccomics',
 'dead',
 'deadly',
 'deal',
 'dealer',
 'dealing',
 'death',
 'debt',
 'deception',
 'decide',
 'decides',
 'decision',
 'deep',
 'defeat',
 'defend',
 'defense',
 'demands',
 'demon',
 'demons',
 'dennisquaid',
 'denzelwashington',
 'depression',
 'desert',
 'desire',
 'desperate',
 'desperately',
 'despite',
 'destiny',
 'destroy',
 'destroyed',
 'destruction',
 'detective',
 'determined',
 'detroit',
 'develops',
 'device',
 'devil',
 'diamond',
 'dianekeaton',
 'did',
 'die',
 'died',
 'dies',
 'different',
 'difficult',
 'diner',
 'dinosaur',
 'directed',
 'director',
 'disappearance',
 'disappears',
 'disaster',
 'discover',
 'discovered',
 'discovers',
 'discovery',
 'disease',
 'distant',
 'district',
 'divorce',
 'divorced',
 'dna',
 'doctor',
 'documentary',
 'does',
 'doesn',
 'dog',
 'doing',
 'don',
 'door',
 'double',
 'dr',
 'dragon',
 'drama',
 'dramatic',
 'drawn',
 'dream',
 'dreams',
 'drewbarrymore',
 'drink',
 'drinking',
 'drive',
 'driven',
 'driver',
 'drug',
 'drugdealer',
 'drugs',
 'duo',
 'duringcreditsstinger',
 'dustinhoffman',
 'duty',
 'dwaynejohnson',
 'dying',
 'dyinganddeath',
 'dysfunctionalfamily',
 'dystopia',
 'early',
 'earth',
 'east',
 'easy',
 'eccentric',
 'eddie',
 'eddiemurphy',
 'edharris',
 'edward',
 'effort',
 'efforts',
 'egypt',
 'elderly',
 'elite',
 'elizabeth',
 'embark',
 'embarks',
 'emily',
 'emma',
 'emperor',
 'empire',
 'employee',
 'encounter',
 'encounters',
 'end',
 'ended',
 'ends',
 'enemies',
 'enemy',
 'engaged',
 'england',
 'english',
 'enlists',
 'ensues',
 'enter',
 'enters',
 'entire',
 'epic',
 'era',
 'escape',
 'escaped',
 'escapes',
 'especially',
 'espionage',
 'estate',
 'estranged',
 'ethanhawke',
 'europe',
 'eve',
 'event',
 'events',
 'eventually',
 'evidence',
 'evil',
 'ewanmcgregor',
 'ex',
 'exactly',
 'executive',
 'existence',
 'exorcism',
 'expedition',
 'experience',
 'experiences',
 'experiment',
 'expert',
 'explosion',
 'explosive',
 'extramaritalaffair',
 'extraordinary',
 'extremeviolence',
 'eye',
 'eyes',
 'face',
 'faced',
 'faces',
 'facing',
 'fact',
 'factory',
 'failed',
 'fairy',
 'fairytale',
 'faith',
 'fall',
 'fallen',
 'falling',
 'fallinginlove',
 'falls',
 'fame',
 'families',
 'family',
 'familyrelationships',
 'famous',
 'fantasy',
 'far',
 'farm',
 'farmer',
 'fashion',
 'fast',
 'fat',
 'fate',
 'father',
 'fatherdaughterrelationship',
 'fathersonrelationship',
 'fbi',
 'fbiagent',
 'fear',
 'fears',
 'feet',
 'fellow',
 'female',
 'femalenudity',
 'festival',
 'fight',
 'fighter',
 'fighting',
 'fights',
 'figure',
 'filled',
 'film',
 'filmmaker',
 'films',
 'final',
 'finally',
 'financial',
 'finding',
 'finds',
 'finish',
 'firm',
 'fish',
 'fistfight',
 'flashback',
 'flight',
 'florida',
 'fly',
 'flying',
 'focuses',
 'follow',
 'following',
 'follows',
 'food',
 'foot',
 'football',
 'force',
 'forced',
 'forces',
 'foreign',
 'forest',
 'forestwhitaker',
 'forever',
 'form',
 'fortune',
 'foster',
 'foundfootage',
 'fox',
 'framed',
 'france',
 'francisco',
 'frank',
 'frankie',
 'fraud',
 'freddy',
 'free',
 'freedom',
 'french',
 'friend',
 'friends',
 'friendship',
 'fu',
 'fugitive',
 'fun',
 'funeral',
 'future',
 'futuristic',
 'galaxy',
 'gambling',
 'game',
 'games',
 'gang',
 'gangs',
 'gangster',
 'garyoldman',
 'gay',
 'genehackman',
 'general',
 'genius',
 'george',
 'georgeclooney',
 'gerardbutler',
 'german',
 'germany',
 'gets',
 'getting',
 'ghost',
 'giant',
 'gift',
 'girl',
 'girlfriend',
 'girls',
 'given',
 'gives',
 'global',
 'globe',
 'goal',
 'god',
 'goes',
 'going',
 'gold',
 'golden',
 'gone',
 'good',
 'goodvsevil',
 'gore',
 'got',
 'government',
 'grace',
 'graduation',
 'grandfather',
 'grandmother',
 'grant',
 'grave',
 'great',
 'greatest',
 'green',
 'ground',
 'group',
 'grow',
 'growing',
 'grown',
 'grows',
 'gruesome',
 'guard',
 'guilt',
 'gun',
 'gunfight',
 'guy',
 'guys',
 'gwynethpaltrow',
 'hacker',
 'half',
 'hall',
 'halloween',
 'hallucination',
 'hand',
 'hands',
 'handsome',
 'happen',
 'happened',
 'happens',
 'happiness',
 'happy',
 'hard',
 'harrisonford',
 'harry',
 'haunted',
 'haunting',
 'having',
 'hawaii',
 'head',
 'headed',
 'heads',
 'health',
 'heart',
 'heist',
 'held',
 'helen',
 'helicopter',
 'hell',
 'help',
 'helping',
 'helps',
 'henry',
 'hero',
 'heroes',
 'heroic',
 'heroin',
 'hidden',
 'hiding',
 'high',
 'highly',
 'highschool',
 'hilarious',
 'hills',
 'hip',
 'hired',
 'hires',
 'historicalfigure',
 'history',
 'hit',
 'hitman',
 'hits',
 'hold',
 'holds',
 'holiday',
 'hollywood',
 'home',
 'hometown',
 'homicide',
 'homosexuality',
 'hong',
 'honor',
 'hop',
 'hope',
 'hopes',
 'hoping',
 'horrific',
 'horror',
 'horse',
 'hospital',
 'host',
 'hostage',
 'hot',
 'hotel',
 'hours',
 'house',
 'huge',
 'hughjackman',
 'human',
 'humanity',
 'humans',
 'humor',
 'hunt',
 'hunter',
 'hunting',
 'husband',
 'ice',
 'icecube',
 'idea',
 'identity',
 'ii',
 'ill',
 'illegal',
 'illness',
 'imax',
 'immediately',
 'immigrant',
 'immortality',
 'important',
 'impossible',
 'inadvertently',
 'including',
 'increasingly',
 'incredible',
 'independence',
 'independentfilm',
 'india',
 'indian',
 'individual',
 'industry',
 'infidelity',
 'influence',
 'inner',
 'innocence',
 'innocent',
 'insanity',
 'inside',
 'inspired',
 'instead',
 'intelligence',
 'international',
 'internet',
 'interview',
 'invasion',
 'inventor',
 'investigate',
 'investigates',
 'investigation',
 'invites',
 'involved',
 'involving',
 'iraq',
 'irish',
 'island',
 'isn',
 'isolated',
 'italian',
 'italy',
 'jack',
 'jackiechan',
 'jackson',
 'jail',
 'jake',
 'jakegyllenhaal',
 'james',
 'jane',
 'japan',
 'japanese',
 'jason',
 'jasonstatham',
 'jealousy',
 'jean',
 'jeffbridges',
 'jenniferaniston',
 'jenniferlopez',
 'jersey',
 'jesus',
 'jewish',
 'jim',
 'jimcarrey',
 'jimmy',
 'job',
 'joe',
 'john',
 'johncusack',
 'johngoodman',
 'johnny',
 'johnnydepp',
 'johnson',
 'johntravolta',
 'join',
 'joins',
 'jonathan',
 'jones',
 'jordan',
 'joseph',
 'journalism',
 'journalist',
 'journey',
 'jr',
 'judelaw',
 'judge',
 'juliannemoore',
 'juliaroberts',
 'julie',
 'jungle',
 'just',
 'justice',
 'kate',
 'katewinslet',
 'keanureeves',
 'kelly',
 'kevin',
 'kevincostner',
 'key',
 'kid',
 'kidnapped',
 'kidnapping',
 'kids',
 'kill',
 'killed',
 'killer',
 'killers',
 'killing',
 'kills',
 'kind',
 'king',
 'kingdom',
 'kirstendunst',
 'kiss',
 'knew',
 'knight',
 'know',
 ...]

In [165]:
#stamming
#['loved','loving','love']
#['love','love','love']

In [168]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [169]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [171]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\User\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [172]:
new_df.head(1)

   movie_id   title                                               tags
0     19995  Avatar  in the 22nd century, a parapleg marin is dispa...

In [173]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2000,stop_words='english')

In [174]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [175]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [176]:
cv.get_feature_names()

['000',
 '10',
 '11',
 '12',
 '14',
 '15',
 '17',
 '18',
 '1930',
 '1950',
 '1960',
 '1970',
 '1980',
 '19th',
 '19thcenturi',
 '20',
 '20th',
 '30',
 '3d',
 '50',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abil',
 'abl',
 'abus',
 'academi',
 'accept',
 'accid',
 'accident',
 'accompani',
 'account',
 'accus',
 'achiev',
 'act',
 'action',
 'actor',
 'actress',
 'actual',
 'adam',
 'adamsandl',
 'adapt',
 'addict',
 'adopt',
 'adult',
 'adulteri',
 'adventur',
 'adventure',
 'advic',
 'affair',
 'affect',
 'africa',
 'african',
 'aftercreditssting',
 'afterlif',
 'ag',
 'age',
 'agent',
 'ago',
 'agre',
 'ahead',
 'aid',
 'air',
 'airplan',
 'airport',
 'alaska',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alic',
 'alien',
 'alieninvas',
 'aliv',
 'alive',
 'alli',
 'allow',
 'alon',
 'alpacino',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'amaz',
 'ambiti',
 'ambush',
 'america',
 'american',
 'americanfootbal',
 'amnesia',
 'amp',
 'ancient',
 'anderson',
 'andi',
 'android',
 'angel',
 'angeles',
 'angelinajoli',
 'anger',
 'ani',
 'anim',
 'ann',
 'anna',
 'annehathaway',
 'annual',
 'anoth',
 'answer',
 'anthonyhopkin',
 'anti',
 'antihero',
 'antoniobandera',
 'anyon',
 'anyth',
 'apart',
 'apocalyps',
 'apocalypt',
 'appear',
 'approach',
 'archaeologist',
 'area',
 'arm',
 'armi',
 'arnoldschwarzenegg',
 'arrang',
 'arrest',
 'arriv',
 'art',
 'arthur',
 'artificialintellig',
 'artist',
 'ask',
 'aspir',
 'assassin',
 'assign',
 'assist',
 'assum',
 'astronaut',
 'asylum',
 'athlet',
 'attack',
 'attempt',
 'attend',
 'attorney',
 'attract',
 'audienc',
 'aunt',
 'australia',
 'australian',
 'author',
 'aveng',
 'avoid',
 'await',
 'awaken',
 'award',
 'away',
 'babi',
 'baby',
 'bachelor',
 'bad',
 'balanc',
 'ballet',
 'band',
 'bank',
 'bar',
 'barri',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedonnovel',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basketbal',
 'batman',
 'battl',
 'beach',
 'bear',
 'beast',
 'beat',
 'beauti',
 'becam',
 'becaus',
 'becom',
 'becominganadult',
 'bed',
 'befor',
 'befriend',
 'begin',
 'believ',
 'belov',
 'ben',
 'benaffleck',
 'benkingsley',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bet',
 'betray',
 'better',
 'big',
 'biggest',
 'biker',
 'billi',
 'billionair',
 'billybobthornton',
 'biographi',
 'bird',
 'birth',
 'birthday',
 'bite',
 'bizarr',
 'black',
 'blackmail',
 'blackpeopl',
 'blind',
 'blood',
 'bloodi',
 'blow',
 'blue',
 'board',
 'boat',
 'bob',
 'bobbi',
 'bodi',
 'bodyguard',
 'bomb',
 'bond',
 'book',
 'border',
 'bore',
 'born',
 'boss',
 'boston',
 'bound',
 'bounti',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'bradpitt',
 'brain',
 'brave',
 'break',
 'brendanfras',
 'brian',
 'bride',
 'bridg',
 'brilliant',
 'bring',
 'britain',
 'british',
 'broadway',
 'broken',
 'brooklyn',
 'brother',
 'brotherbrotherrelationship',
 'brothersisterrelationship',
 'brought',
 'brown',
 'brucewilli',
 'brutal',
 'bu',
 'buddi',
 'build',
 'bulli',
 'buri',
 'burn',
 'busi',
 'business',
 'businessman',
 'buy',
 'cabin',
 'california',
 'calvin',
 'came',
 'camera',
 'camerondiaz',
 'camp',
 'campaign',
 'canada',
 'canadian',
 'cancer',
 'capabl',
 'capit',
 'captain',
 'captiv',
 'captur',
 'car',
 'carchas',
 'carcrash',
 'care',
 'career',
 'carl',
 'carrac',
 'carri',
 'carter',
 'case',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'catch',
 'cateblanchett',
 'catherinekeen',
 'cathol',
 'caught',
 'caus',
 'cave',
 'celebr',
 'center',
 'centuri',
 'century',
 'certain',
 'chain',
 'challeng',
 'champion',
 'championship',
 'chanc',
 'chang',
 'chao',
 'charact',
 'charg',
 'charl',
 'charli',
 'charlie',
 'charlizetheron',
 'charm',
 'chase',
 'cheat',
 'chicago',
 'chief',
 'child',
 'childhood',
 'children',
 'china',
 'chines',
 'choic',
 'choos',
 'chosen',
 'chri',
 'christian',
 'christianbal',
 'christma',
 'christopherplumm',
 'chronicl',
 'church',
 'cia',
 'circu',
 'citi',
 'city',
 'civil',
 'claim',
 'clash',
 'class',
 'classic',
 'clean',
 'clear',
 'clerk',
 'climb',
 'clinteastwood',
 'clock',
 'clone',
 'close',
 'closer',
 'club',
 'clue',
 'coach',
 'cocain',
 'code',
 'cold',
 'coldwar',
 'colinfarrel',
 'colleagu',
 'collect',
 'colleg',
 'college',
 'collid',
 'coloni',
 'color',
 'coma',
 'combat',
 'combin',
 'come',
 'comedi',
 'comedian',
 'comedy',
 'comic',
 'comingofag',
 'command',
 'commit',
 'common',
 'commun',
 'compani',
 'company',
 'compet',
 'competit',
 'complet',
 'complex',
 'complic',
 'comput',
 'concert',
 'confid',
 'conflict',
 'confront',
 'connect',
 'connor',
 'consequences',
 'consid',
 'conspiraci',
 'contact',
 'contain',
 'contest',
 'continu',
 'contract',
 'control',
 'controversi',
 'convict',
 'convinc',
 'cook',
 'cooper',
 'cop',
 'cope',
 'corpor',
 'corps',
 'corrupt',
 'cost',
 'count',
 'countri',
 'country',
 'coupl',
 'couple',
 'courag',
 'cours',
 'court',
 'cousin',
 'cover',
 'cowardli',
 'crack',
 'crash',
 'crazi',
 'creat',
 'creatur',
 'crew',
 'crime',
 'crimefight',
 'crimin',
 'crisi',
 'critic',
 'crook',
 'cross',
 'crush',
 'cuba',
 'cult',
 'cultur',
 'cure',
 'current',
 'curs',
 'cut',
 'dad',
 'daili',
 'dan',
 'danc',
 'dancer',
 'danger',
 'daniel',
 'danni',
 'dannydevito',
 'dare',
 'dark',
 'darkcomedi',
 'date',
 'daughter',
 'david',
 'day',
 'dccomic',
 'dead',
 'deadli',
 'deal',
 'dealer',
 'death',
 'debt',
 'decad',
 'decept',
 'decid',
 'decis',
 'deep',
 'defeat',
 'defend',
 'defens',
 'deliv',
 'demand',
 'demon',
 'dennisquaid',
 'denzelwashington',
 'depict',
 'depress',
 'descend',
 'desert',
 'design',
 'desir',
 'desper',
 'despit',
 'destin',
 'destroy',
 'destruct',
 'detect',
 'determin',
 'detroit',
 'devast',
 'develop',
 'devil',
 'diamond',
 'dianekeaton',
 'did',
 'die',
 'dies',
 'differ',
 'difficult',
 'diner',
 'dinosaur',
 'direct',
 'director',
 'disappear',
 'disast',
 'discov',
 'discoveri',
 'disfigur',
 'distant',
 'district',
 'disturb',
 'divorc',
 'dna',
 'doctor',
 'document',
 'documentari',
 'doe',
 'doesn',
 'dog',
 'doll',
 'dolphin',
 'domin',
 'don',
 'door',
 'doubl',
 'doubt',
 'dr',
 'drag',
 'dragon',
 'drama',
 'dramat',
 'draw',
 'drawn',
 'dream',
 'dreams',
 'drewbarrymor',
 'drink',
 'drive',
 'driven',
 'driver',
 'drop',
 'drug',
 'drugaddict',
 'drugdeal',
 'drugs',
 'dump',
 'duo',
 'dure',
 'duringcreditssting',
 'dustinhoffman',
 'duti',
 'dwaynejohnson',
 'dyinganddeath',
 'dysfunctionalfamili',
 'dystopia',
 'earli',
 'earn',
 'earth',
 'easi',
 'east',
 'eat',
 'eccentr',
 'econom',
 'eddi',
 'eddiemurphi',
 'edharri',
 'edward',
 'edwardnorton',
 'effort',
 'egg',
 'egypt',
 'elderli',
 'elit',
 'elizabeth',
 'embark',
 'emerg',
 'emma',
 'emot',
 'emperor',
 'employ',
 'employe',
 'encount',
 'end',
 'enemi',
 'enforc',
 'engag',
 'engin',
 'england',
 'english',
 'enlist',
 'enter',
 'entertain',
 'entir',
 'epic',
 'era',
 'escap',
 'especi',
 'establish',
 'estat',
 'estrang',
 'ethanhawk',
 'europ',
 'eve',
 'event',
 'events',
 'eventu',
 'everi',
 'everyon',
 'everyth',
 'evid',
 'evil',
 'ewanmcgregor',
 'ex',
 'exact',
 'exactli',
 'examin',
 'excit',
 'execut',
 'exist',
 'expect',
 'expedit',
 'experi',
 'expert',
 'explor',
 'explos',
 'expos',
 'extramaritalaffair',
 'extraordinari',
 'extrem',
 'extremeviol',
 'eye',
 'face',
 'fact',
 'fail',
 'fairi',
 'fairytal',
 'faith',
 'fall',
 'fallen',
 'fallinginlov',
 'fame',
 'famili',
 'family',
 'familyrelationship',
 'famou',
 'fan',
 'fantasi',
 'fantast',
 'far',
 'farm',
 'farmer',
 'fashion',
 'fast',
 'fat',
 'fatal',
 'fate',
 'father',
 'fatherdaughterrelationship',
 'fathersonrelationship',
 'fbi',
 'fbiagent',
 'fear',
 'featur',
 'feder',
 'feel',
 'feet',
 'fellow',
 'femal',
 'femalenud',
 'femaleprotagonist',
 'fiancé',
 'fiction',
 'field',
 'fierc',
 'fight',
 'fighter',
 'figur',
 'film',
 'filmmak',
 'final',
 'financi',
 'finish',
 'firm',
 'fish',
 'fistfight',
 'fit',
 'flashback',
 'flee',
 'fli',
 'flight',
 'flood',
 'florida',
 'focus',
 'follow',
 'food',
 'foot',
 'footbal',
 'forc',
 'force',
 'foreign',
 'forest',
 'forestwhitak',
 'forev',
 'forever',
 'form',
 'fortun',
 'foster',
 'foundfootag',
 'fox',
 'frame',
 'franc',
 'france',
 'francisco',
 'frank',
 'fraud',
 'freddi',
 'free',
 'freedom',
 'french',
 'friend',
 'friends',
 'friendship',
 'frighten',
 'fu',
 'fugit',
 'fulfil',
 'fun',
 'fund',
 'funer',
 'futur',
 'future',
 'futurist',
 'gain',
 'gambl',
 'game',
 'gang',
 'gangster',
 'garyoldman',
 'gather',
 'gay',
 'genehackman',
 'gener',
 'genet',
 'geniu',
 'georg',
 'georgeclooney',
 'gerardbutl',
 'german',
 'germani',
 'ghost',
 'giant',
 'gift',
 'girl',
 'girlfriend',
 'given',
 'global',
 'globe',
 'goal',
 'god',
 'goe',
 'gold',
 'golden',
 'gone',
 'good',
 'goodvsevil',
 'gordon',
 'gore',
 'got',
 'govern',
 'grace',
 'graduat',
 'grant',
 'grave',
 'great',
 'greatest',
 'greek',
 'green',
 'griev',
 'ground',
 'group',
 'grow',
 'grown',
 'gruesom',
 'guard',
 'guest',
 'guid',
 'guilt',
 'gun',
 'gunfight',
 'guy',
 'ha',
 'hacker',
 'half',
 'hall',
 'halloween',
 'hallucin',
 'hand',
 'handsom',
 'hang',
 'happen',
 'happi',
 'harbor',
 'hard',
 'harri',
 'harrisonford',
 'hatch',
 'haunt',
 'hawaii',
 'head',
 'health',
 'hear',
 'heart',
 'heaven',
 'heist',
 'held',
 'helen',
 'helicopt',
 'hell',
 'help',
 'henri',
 'hero',
 'heroic',
 'heroin',
 'hi',
 'hidden',
 'hide',
 'high',
 'highli',
 'highschool',
 'hijack',
 'hilari',
 'hill',
 'hip',
 'hire',
 'histor',
 'histori',
 'historicalfigur',
 'history',
 'hit',
 'hitman',
 'hold',
 'holiday',
 'hollywood',
 'home',
 'hometown',
 'homicid',
 'homosexu',
 'hong',
 'honor',
 'hood',
 'hoodlum',
 'hook',
 'hop',
 'hope',
 'horrif',
 'horrifi',
 'horror',
 'hors',
 'hospit',
 'host',
 'hostag',
 'hostil',
 'hot',
 'hotel',
 'hour',
 'hous',
 'house',
 'howev',
 'huge',
 'hughjackman',
 'human',
 'humanity',
 'humor',
 'hunt',
 'hunter',
 'husband',
 'ice',
 'icecub',
 'idea',
 'ident',
 'identity',
 'idol',
 'idyl',
 'ii',
 'ill',
 'illeg',
 'imagin',
 'imax',
 'immedi',
 'immigr',
 'immort',
 'import',
 'imposs',
 'imprison',
 'inadvert',
 'includ',
 'increasingli',
 'incred',
 'independ',
 'independentfilm',
 'india',
 'indian',
 'individu',
 'industri',
 'infidel',
 'infiltr',
 'influenc',
 'inform',
 'inherit',
 'initi',
 'inner',
 'innoc',
 'insan',
 'insid',
 'inspir',
 'instal',
 'instead',
 'intellig',
 'intend',
 'intent',
 'intern',
 'internet',
 'interview',
 'intrigu',
 'introduc',
 'invad',
 'invas',
 'invent',
 'inventor',
 'investig',
 'invis',
 'invit',
 'involv',
 'iraq',
 'irish',
 'island',
 'isn',
 'isol',
 'itali',
 'italian',
 'jack',
 'jackiechan',
 'jackson',
 'jail',
 'jake',
 'jakegyllenha',
 'jame',
 'jane',
 'japan',
 'japanes',
 'jason',
 'jasonstatham',
 'jay',
 'jealousi',
 'jean',
 'jeffbridg',
 'jenniferaniston',
 'jenniferlopez',
 'jersey',
 'jess',
 'jew',
 'jewish',
 'jim',
 'jimcarrey',
 'jimmi',
 'joaquinphoenix',
 'job',
 'joe',
 'john',
 'johncusack',
 'johngoodman',
 'johnni',
 'johnnydepp',
 'johnson',
 'johntravolta',
 'join',
 'jon',
 'jonathan',
 ...]

In [177]:
from sklearn.metrics.pairwise import cosine_similarity

In [179]:
similarity=cosine_similarity(vectors)

In [180]:
similarity.shape

(4806, 4806)

In [217]:
def recommend(movie):
    movie_index =new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key = lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [212]:
sorted(list(enumerate(similarity[1])),reverse=True,key = lambda x:x[1])[1:6]

[(12, 0.3763089045031909),
 (17, 0.31171460007967877),
 (199, 0.3072549338995135),
 (3572, 0.2631174057921088),
 (216, 0.24535824603285925)]

In [219]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
10th & Wolf
Superman

In [216]:
new_df.iloc[1216].title

'Aliens vs Predator: Requiem'

In [220]:
import pickle

In [223]:
pickle.dump(new_df.to_dict(),open('movies_dict.pkl','wb'))

In [224]:
new_df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4805,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4807,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4808,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [225]:
pickle.dump(similarity,open('similarity.pkl','wb'))